CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100),
    username   VARCHAR(50),
    email      VARCHAR(50),
    phone      VARCHAR(20),
    website    VARCHAR(100),
    created_by BIGINT,
    created_at TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);